### ISSUE TITLE
New Language - Translation for Spanish of Ecuador  (es-EC)

### ISSUE THREAD

**Issue by fabyc** [frappe/translator#103] opened 2017-04-01 23:33 UTC
I would like to translate to Spanish language of Ecuador.

Thanks

**Comment by fabyc** [comment] 2017-04-01 23:35
Better description of request.

**Comment by mbauskar** [comment] 2017-09-11 05:00
duplicate of https://github.com/frappe/translator/issues/111

**Closed by mbauskar** 2017-09-11 05:00 UTC
